name             'tal_tomcat'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures tal_tomcat'
long_description 'Installs/Configures tal_tomcat'
version          '0.1.0'
